sudo : required
services:
  - docker
before_install: 
  - docker build -t arabinda338nitc/docker-react -f Dockerfile.dev .
script: 
  - docker run arabinda338nitc/docker-react npm run test -- --coverage

# -- --coverage is added to ensure travisCI exits the test, otherwise it will keep running the test and never exit.
